FROM php:7.4-apache

RUN apt-get update

RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# PHP extensions
RUN docker-php-ext-install pdo pdo_mysql mysqli

RUN a2enmod rewrite